import Navigation from '@/components/common/Navigation'
import 'ress'
import './globals.css'
import styles from './layout.module.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.BaseWrapper}>
          <header className={styles.NavigationWrapper}>
            <Navigation />
          </header>
          <main className={styles.ContentWrapper}>{children}</main>
        </div>
      </body>
    </html>
  )
}
